### ISSUE TITLE
Connecte la node sans erreur

### ISSUE THREAD

**Issue by jvtrudel** [dravedev/devops#22]
La connection d'une node au cluster kubernetes échoue de manière aléatoire. Plus il y a de nodes déconnectées, plus il y a de probabilité d'échec.

Dans `roles/grappe/main.yml:

```
- name: choisi une node au hasard pour obtenir la ligne de commande pour joindre la grappe
  become: no
  command:
    "ssh -o ConnectTimeout=3 -o StrictHostKeyChecking=no {{master}} 'microk8s add-node'"
  register: output
  vars:
    master: "{{ (groups['all'] | difference([inventory_hostname_short]) | random) }}"
  retries: 3
  until: output.rc == 0
  failed_when: "'run the following' not in output.stdout"
  changed_when: false
  tags: [ha,join-node,add-node]
  ```
  
  On sélectionne au hasard un master à partir des nodes dans l'inventaire. Mais rien ne garantie que ce serveur est accessible, ni qu'il est connecté à la grappe.
  
  Il faudrait:
  
  - s'assurer que le serveur sur lequel est exécuté `'microk8s add-node'` est accessible
  - s'assurer que le serveur sélectionné est inscrit sur la grappe kubectl
  - s'assurer que l'on utilise l'interface vpncloud pour s'y connectée
    
```
    join_command: "{{output.stdout_lines[-1]}}"
```
